repos:
- repo: local
  hooks:
  - id: version-check
    name: Check the package version
    language: system
    entry: ./build-tools/version.py update
    pass_filenames: false
  - id: gen-cli-docs
    name: Generate CLI docs
    language: system
    entry: make docs
    pass_filenames: false
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v3.4.0'
  hooks:
  - id: check-merge-conflict
    exclude: "rst$"
- repo: https://github.com/asottile/yesqa
  rev: v1.2.2
  hooks:
  - id: yesqa
- repo: https://github.com/aio-libs/sort-all
  rev: v1.1.0
  hooks:
  - id: sort-all
- repo: https://github.com/PyCQA/isort
  rev: '5.7.0'
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: '20.8b1'
  hooks:
  - id: black
    language_version: python3 # Should be a command that runs python3.6+
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v3.4.0'
  hooks:
  - id: check-case-conflict
  - id: check-json
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: check-added-large-files
  - id: end-of-file-fixer
    exclude: "[.]md$"
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    exclude: "[.]ref$"
  - id: check-symlinks
  - id: debug-statements
  - id: file-contents-sorter
    files: |
      (?x)^(
        .gitignore|
        neuro-sdk/docs/spelling_wordlist.txt
      )$
- repo: https://github.com/asottile/pyupgrade
  rev: 'v2.9.0'
  hooks:
  - id: pyupgrade
    args: ['--py36-plus']
- repo: https://gitlab.com/pycqa/flake8
  rev: '3.8.4'
  hooks:
  - id: flake8
    exclude: "^neuro-sdk/docs/"
